### ISSUE TITLE
Add Webhook Events Structs

### ISSUE THREAD

**Issue by JeanVydes** [VarunPotti/lemonsqueezy.rs#1]
https://docs.lemonsqueezy.com/help/webhooks

this can be useful, for example, create the endpoint for be called by the webhook, and access to payload data.
dont forget to return a 200 status to verify that the webhook have been captured.

**Comment by VarunPotti** [comment]
Great Idea! Will take a look at this once I am done with my exams. 

Though, I think the actual structure is quite similar to the structs I have right now. I need to build the `meta` and the `data` types for it to work completely and do some magic for it to detect if the struct in `attributes` is an order, subscription, etc.
